{% set name = "cassandra-driver" %}
{% set version = "3.18.0" %}
{% set sha256 = "71c5bcded827deaa5da8fcca84891eb9024520653f49c9ce49d508439b3b2af1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py build build_ext -I${PREFIX}/include -L${PREFIX}/lib install --single-version-externally-managed --record record.txt  # [not win]
  script: python setup.py install --no-cython --single-version-externally-managed --record record.txt  # [win]
  skip: True

requirements:
  build:
    - python
    - setuptools
    - cython
    - libev  # [not win]
    - msinttypes  # [win and py2k]

  run:
    - python
    - numpy
    - six >=1.9
    - futures <=2.2.0  # [py2k]
    - libev  # [not win]

test:
  imports:
    - cassandra
    - cassandra.cqlengine
    - cassandra.io
    - cassandra.numpy_parser  # [not win]

about:
  home: http://github.com/datastax/python-driver
  license: Apache
  license_family: Apache
  license_file: LICENSE
  summary: 'Python driver for Cassandra'
  description: |
    A modern, feature-rich and highly-tunable Python client library for Apache Cassandra (2.1+) 
    using exclusively Cassandra’s binary protocol and Cassandra Query Language v3.
  doc_url: http://datastax.github.io/python-driver/api/index.html
  dev_url: http://github.com/datastax/python-driver

extra:
  recipe-maintainers:
    - petercable
    - anirrudh
